baseURL = "http://www.connorreardon.com.s3-website.us-east-2.amazonaws.com"
languageCode = "en-us"
title = "Connor Reardon"

[params]
    ## Style ##
    styleBaseURL = "http://www.connorreardon.com.s3-website.us-east-2.amazonaws.com"
    image = "default.jpg"

    ## Intro ##
    firstName = "Connor"
    lastName = "Reardon"
    intro = "Hi, I’m Connor. I study finance and math at Wake Forest University. My interests include studying the global marketplace and engaging people from different cultures and backgrounds. Upon graduation in May 2020, I’m looking for a full-time position where I can further explore the world of finance."
    resume = "./pdf/ReardonResume.pdf"
    firstInitial = "C"
    middleInitial = "D"
    lastInitial = "RN"

    ## Social ##
    facebook = "https://www.facebook.com/connor.reardon.35"
    twitter = ""
    linkedin = "https://www.linkedin.com/in/connor-reardon-677658147/"

    ## Professional Experience ##
    professional_1 = "Corporate Operations Intern ('18)"
    professional_1_link = "https://www.theblackdog.com/"
    professional_1_link_word = "The Black Dog Tavern Co."

    professional_2 = "Research Analyst ('19)"
    professional_2_link = "http://www.deacon-fund.com/"
    professional_2_link_word = "Deacon Fund Club"

    ## Relevant Coursework ##
    course_1 = "Principles of Finance"
    course_2 = "Quantitative Analysis I"
    course_3 = "Introduction to Accounting"
    course_4 = "Linear Algebra"

    ## Leadership ##
    leadership_1 = "Organizer ('17, '18)"
    leadership_1_link = "https://team.curethekids.org/campaign/deacs-vs-cancer-2018/c174401"
    leadership_1_link_word = "Deacs vs. Cancer"

    leadership_2 = "Active Member ('17-'19)"
    leadership_2_link = "http://alphasigmaphi.org/"
    leadership_2_link_word = "Alpha Sigma Phi Fraternity"

    ## Skills ##
    skill_1 = "R"
    skill_2 = "Excel (Advanced)"
    skill_3 = "Spanish (Working Knowledge)"
    skill_4 = "Powerpoint"

    ## References ##
    reference_1 = "Connor is a thoughtful individual, often pausing in conversation to deliberate the words he says. In this, he arrives as thoughts and conversations far more intricate and involved than those that are expected of him."
    reference_1_author = "Guha Rajan, Deacon Fund Club Member"

    reference_2 = "Connor is a thoughtful individual, often pausing in conversation to deliberate the words he says. In this, he arrives as thoughts and conversations far more intricate and involved than those that are expected of him."
    reference_2_author = "Guha Rajan, Deacon Fund Club Member"

    reference_3 = "Connor is a thoughtful individual, often pausing in conversation to deliberate the words he says. In this, he arrives as thoughts and conversations far more intricate and involved than those that are expected of him."
    reference_3_author = "Guha Rajan, Deacon Fund Club Member"

    ## Footer ##
    email = "rearcd16@wfu.edu"

    article_1 = "Lyft Off? The First Ride Sharing IPO!"
    article_1_link = "http://aswathdamodaran.blogspot.com/2019/03/lyft-off-first-ride-sharing-ipo.html"
    article_1_caption = "From Musings on Markets - Finance Professor Aswath Damodaran on Lyft pre-IPO"

    article_2 = "Uber's Coming out Party: Personal Mobility Pioneer or Car Service on Steroids?"
    article_2_link = "https://www.bloombergquint.com/opinion/ubers-coming-out-party-personal-mobility-pioneer-or-car-service-on-steroids"
    article_2_caption = "More from Musings on Markets - Prof. Damodaran on Uber"

    article_3 = "Tesla: Anatomy of a Run-Up Value Creation or Investor Sentiment?"
    article_3_link = "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2429778"
    article_3_caption = "You guessed it - Finance Professor Aswath Damodaran on Tesla"